name: Deploy DIY Smart Assistant to cheasydiy.com

on:
  push:
    branches:
      - aws-deployment
  pull_request:
    branches:
      - aws-deployment
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: cheasydiy/backend
  ECR_REPOSITORY_FRONTEND: cheasydiy/frontend
  ECS_CLUSTER: cheasydiy-production-cluster
  ECS_SERVICE_BACKEND: cheasydiy-production-backend
  S3_BUCKET_FRONTEND: cheasydiy-production-frontend

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      working-directory: ./DIY-Smart-Assistant-V2/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install pytest pytest-cov
      continue-on-error: true

    - name: Run backend tests
      working-directory: ./DIY-Smart-Assistant-V2/backend
      run: |
        echo "Skipping backend tests for now"
        # pytest --cov=. --cov-report=xml
      continue-on-error: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: ./DIY-Smart-Assistant-V2/frontend
      run: npm ci
      continue-on-error: true

    - name: Run frontend tests
      working-directory: ./DIY-Smart-Assistant-V2/frontend
      run: |
        echo "Skipping frontend tests for now"
        # npm run test:unit
      continue-on-error: true

  build-and-deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest
    needs: test
    if: always() && github.ref == 'refs/heads/aws-deployment'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push backend image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ./DIY-Smart-Assistant-V2/backend
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest

    - name: Build, tag, and push frontend image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
        VITE_API_URL: https://api.cheasydiy.com
      working-directory: ./DIY-Smart-Assistant-V2/frontend
      run: |
        docker build \
          --build-arg VITE_API_URL=$VITE_API_URL \
          -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest

    - name: Run Database Migrations
      run: |
        # Run database migrations before deploying new version
        # Create a temporary ECS task to run migrations
        
        # Get the current task definition
        TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE_BACKEND }} --query 'services[0].taskDefinition' --output text)
        
        # Run migration task
        aws ecs run-task \
          --cluster ${{ env.ECS_CLUSTER }} \
          --task-definition $TASK_DEF_ARN \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-023b2d055fd11ede0,subnet-02ee4fc4ee285ca79],securityGroups=[sg-052667c608db180e7],assignPublicIp=DISABLED}" \
          --overrides '{
            "containerOverrides": [{
              "name": "backend",
              "command": ["python", "-m", "alembic", "upgrade", "head"]
            }]
          }' \
          --query 'tasks[0].taskArn' --output text > migration_task_arn.txt
        
        # Wait for migration to complete
        MIGRATION_TASK=$(cat migration_task_arn.txt)
        aws ecs wait tasks-stopped --cluster ${{ env.ECS_CLUSTER }} --tasks $MIGRATION_TASK
        
        # Check if migration succeeded
        EXIT_CODE=$(aws ecs describe-tasks --cluster ${{ env.ECS_CLUSTER }} --tasks $MIGRATION_TASK --query 'tasks[0].containers[0].exitCode' --output text)
        
        if [ "$EXIT_CODE" != "0" ]; then
          echo "❌ Database migration failed with exit code: $EXIT_CODE"
          exit 1
        fi
        
        echo "✅ Database migrations completed successfully"

    - name: Update Backend Service to use Fargate Spot with Fallback
      run: |
        # Update service to use mixed capacity provider strategy for optimal cost/availability
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE_BACKEND }} \
          --capacity-provider-strategy \
            capacityProvider=FARGATE_SPOT,weight=4,base=0 \
            capacityProvider=FARGATE,weight=1,base=0 \
          --force-new-deployment \
          --deployment-configuration "maximumPercent=200,minimumHealthyPercent=50"
        
        echo "💰 Backend service updated to use 80% Fargate Spot + 20% Fargate fallback"
        echo "📊 Expected cost savings: ~56% compared to 100% regular Fargate"

    - name: Wait for backend service to stabilize
      run: |
        aws ecs wait services-stable \
          --cluster ${{ env.ECS_CLUSTER }} \
          --services ${{ env.ECS_SERVICE_BACKEND }}
        
        echo "✅ Backend service deployment completed"

  deploy-s3-cloudfront:
    name: Deploy Frontend to S3 and CloudFront
    runs-on: ubuntu-latest
    needs: test
    if: always() && github.ref == 'refs/heads/aws-deployment'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and build
      working-directory: ./DIY-Smart-Assistant-V2/frontend
      env:
        VITE_API_URL: https://api.cheasydiy.com
      run: |
        npm ci
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to S3
      working-directory: ./DIY-Smart-Assistant-V2/frontend
      run: |
        aws s3 sync dist/ s3://${{ env.S3_BUCKET_FRONTEND }} --delete

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [build-and-deploy, deploy-s3-cloudfront]
    if: always()
    
    steps:
    - name: Send notification
      run: |
        if [ "${{ needs.build-and-deploy.result }}" == "success" ] && [ "${{ needs.deploy-s3-cloudfront.result }}" == "success" ]; then
          echo "✅ Deployment successful!"
          echo "🐳 Docker images built and pushed to ECR"
          echo "📦 Frontend deployed to S3/CloudFront"
          echo "⚙️ ECS services updated (if they exist)"
          # Add notification logic here (Slack, email, etc.)
        else
          echo "❌ Deployment failed!"
          echo "Build and Deploy: ${{ needs.build-and-deploy.result }}"
          echo "S3/CloudFront: ${{ needs.deploy-s3-cloudfront.result }}"
          # Add failure notification logic here
        fi